-- HR Management Tables (Payroll & Appraisals)

CREATE TABLE IF NOT EXISTS public.payroll (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  month VARCHAR(20) NOT NULL,
  year INT NOT NULL,
  base_salary DECIMAL(10,2) DEFAULT 0,
  bonuses DECIMAL(10,2) DEFAULT 0,
  deductions DECIMAL(10,2) DEFAULT 0,
  net_salary DECIMAL(10,2) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'unpaid', -- unpaid, paid
  payment_date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.appraisals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  reviewer_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  review_period VARCHAR(50) NOT NULL,
  performance_score INT NOT NULL, -- 1-10
  feedback TEXT,
  goals_achieved TEXT,
  areas_of_improvement TEXT,
  status VARCHAR(20) DEFAULT 'draft', -- draft, finalized
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies
ALTER TABLE public.payroll ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appraisals ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "SuperAdmins and Board can view payroll" ON public.payroll;
CREATE POLICY "SuperAdmins and Board can view payroll"
  ON public.payroll FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid() AND users.role IN ('super_admin', 'board_member')
    )
    OR user_id = auth.uid()
  );

DROP POLICY IF EXISTS "SuperAdmins can manage payroll" ON public.payroll;
CREATE POLICY "SuperAdmins can manage payroll"
  ON public.payroll FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid() AND users.role = 'super_admin'
    )
  );

DROP POLICY IF EXISTS "SuperAdmins and Board can view appraisals" ON public.appraisals;
CREATE POLICY "SuperAdmins and Board can view appraisals"
  ON public.appraisals FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid() AND users.role IN ('super_admin', 'board_member')
    )
    OR user_id = auth.uid()
  );

DROP POLICY IF EXISTS "SuperAdmins can manage appraisals" ON public.appraisals;
CREATE POLICY "SuperAdmins can manage appraisals"
  ON public.appraisals FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE users.id = auth.uid() AND users.role = 'super_admin'
    )
  );
