-- ============================================================
-- Staff Documents, Appraisals, Leave Requests, Workspace Docs
-- Run this in Supabase SQL editor
-- ============================================================

-- Staff Documents (joining letter, payslip, NDA, etc.)
CREATE TABLE IF NOT EXISTS public.staff_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  uploaded_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  doc_type VARCHAR(50) NOT NULL DEFAULT 'other',
  title VARCHAR(300) NOT NULL,
  doc_url TEXT,
  month VARCHAR(10),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Staff Appraisals (linked to My Profile page)
CREATE TABLE IF NOT EXISTS public.staff_appraisals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  reviewed_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  period VARCHAR(100) NOT NULL,
  rating NUMERIC(3,1) DEFAULT 0,
  performance_score INT DEFAULT 0,
  goals_met INT DEFAULT 0,
  feedback TEXT,
  strengths TEXT,
  areas_to_improve TEXT,
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Leave Requests
CREATE TABLE IF NOT EXISTS public.leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  leave_type VARCHAR(50) NOT NULL DEFAULT 'casual',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  days INT NOT NULL DEFAULT 1,
  reason TEXT NOT NULL,
  status VARCHAR(20) DEFAULT 'pending',
  approved_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Workspace / Shared Team Documents
CREATE TABLE IF NOT EXISTS public.workspace_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  updated_by BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  title VARCHAR(300) NOT NULL,
  doc_type VARCHAR(50) DEFAULT 'document',
  content TEXT,
  doc_url TEXT,
  tags TEXT[] DEFAULT '{}',
  department VARCHAR(100),
  is_pinned BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Also ensure payroll table exists (from setup_hr_tables.sql - safe to re-run)
CREATE TABLE IF NOT EXISTS public.payroll (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  month VARCHAR(20) NOT NULL,
  year INT NOT NULL,
  base_salary DECIMAL(10,2) DEFAULT 0,
  bonuses DECIMAL(10,2) DEFAULT 0,
  deductions DECIMAL(10,2) DEFAULT 0,
  net_salary DECIMAL(10,2) DEFAULT 0,
  status VARCHAR(20) DEFAULT 'unpaid',
  payment_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Also ensure appraisals table exists
CREATE TABLE IF NOT EXISTS public.appraisals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
  reviewer_id BIGINT REFERENCES public.users(id) ON DELETE SET NULL,
  review_period VARCHAR(50) NOT NULL,
  performance_score INT NOT NULL DEFAULT 0,
  feedback TEXT,
  goals_achieved TEXT,
  areas_of_improvement TEXT,
  status VARCHAR(20) DEFAULT 'draft',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- RLS Policies
-- ============================================================

ALTER TABLE public.staff_documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_appraisals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.leave_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workspace_documents ENABLE ROW LEVEL SECURITY;

-- staff_documents: own doc or admin/super_admin can see
DROP POLICY IF EXISTS "staff_documents_read" ON public.staff_documents;
CREATE POLICY "staff_documents_read" ON public.staff_documents FOR SELECT
  USING (
    user_id = (SELECT id FROM public.users WHERE email = auth.jwt()->>'email' LIMIT 1)
    OR EXISTS (
      SELECT 1 FROM public.users
      WHERE email = auth.jwt()->>'email'
        AND role IN ('super_admin', 'admin', 'board_member')
    )
  );

DROP POLICY IF EXISTS "staff_documents_insert" ON public.staff_documents;
CREATE POLICY "staff_documents_insert" ON public.staff_documents FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.users WHERE email = auth.jwt()->>'email')
  );

DROP POLICY IF EXISTS "staff_documents_delete" ON public.staff_documents;
CREATE POLICY "staff_documents_delete" ON public.staff_documents FOR DELETE
  USING (
    user_id = (SELECT id FROM public.users WHERE email = auth.jwt()->>'email' LIMIT 1)
    OR EXISTS (
      SELECT 1 FROM public.users
      WHERE email = auth.jwt()->>'email'
        AND role IN ('super_admin', 'admin')
    )
  );

-- staff_appraisals: own or admin
DROP POLICY IF EXISTS "staff_appraisals_read" ON public.staff_appraisals;
CREATE POLICY "staff_appraisals_read" ON public.staff_appraisals FOR SELECT
  USING (
    user_id = (SELECT id FROM public.users WHERE email = auth.jwt()->>'email' LIMIT 1)
    OR EXISTS (
      SELECT 1 FROM public.users
      WHERE email = auth.jwt()->>'email'
        AND role IN ('super_admin', 'admin', 'board_member')
    )
  );

DROP POLICY IF EXISTS "staff_appraisals_all" ON public.staff_appraisals;
CREATE POLICY "staff_appraisals_all" ON public.staff_appraisals FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE email = auth.jwt()->>'email'
        AND role IN ('super_admin', 'admin')
    )
  );

-- leave_requests: own or admin
DROP POLICY IF EXISTS "leave_requests_read" ON public.leave_requests;
CREATE POLICY "leave_requests_read" ON public.leave_requests FOR SELECT
  USING (
    user_id = (SELECT id FROM public.users WHERE email = auth.jwt()->>'email' LIMIT 1)
    OR EXISTS (
      SELECT 1 FROM public.users
      WHERE email = auth.jwt()->>'email'
        AND role IN ('super_admin', 'admin', 'board_member')
    )
  );

DROP POLICY IF EXISTS "leave_requests_insert" ON public.leave_requests;
CREATE POLICY "leave_requests_insert" ON public.leave_requests FOR INSERT
  WITH CHECK (
    EXISTS (SELECT 1 FROM public.users WHERE email = auth.jwt()->>'email')
  );

DROP POLICY IF EXISTS "leave_requests_admin" ON public.leave_requests;
CREATE POLICY "leave_requests_admin" ON public.leave_requests FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM public.users
      WHERE email = auth.jwt()->>'email'
        AND role IN ('super_admin', 'admin')
    )
  );

-- workspace_documents: all staff can read, only admins can manage
DROP POLICY IF EXISTS "workspace_documents_read" ON public.workspace_documents;
CREATE POLICY "workspace_documents_read" ON public.workspace_documents FOR SELECT
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE email = auth.jwt()->>'email')
  );

DROP POLICY IF EXISTS "workspace_documents_write" ON public.workspace_documents;
CREATE POLICY "workspace_documents_write" ON public.workspace_documents FOR ALL
  USING (
    EXISTS (SELECT 1 FROM public.users WHERE email = auth.jwt()->>'email')
  );
